services:
  weasyprint:
    build:
      context: .
      dockerfile: Dockerfile
    image: 4teamwork/weasyprint:latest
    container_name: weasyprint
    restart: always
    ports:
      - "5001:8080"
    environment:
      WEASYPRINT_ALLOWED_URLS_PATTERN: '^https:\/\/fonts\.googleapis\.com.*|^https:\/\/fonts\.gstatic\.com.*'
